#!/usr/bin/env python
__version__    = "0.0.1"
__date__       = "07.03.2013"
__author__     = "Joseph Zeranski"
__maintainer__ = "Joseph Zeranski"
__email__      = "madsc13ntist gmail.com"
__copyright__  = "Copyright 2013, " + __author__
__license__    = "MIT"
__status__     = "Prototype"
__credits__    = [""]
__description__= "Use IDAPython to create a yara signature from a byte selection in IDA Pro"

####################### MIT License ####################### 
# Copyright (c) 2013 Joseph Zeranski
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
###########################################################

import os
from time import strftime

VERBOSE = True
datestamp = strftime("%Y.%m.%d %H:%M:%S")
current_user = os.getenv("USERNAME")
segment = SegName(SelStart())


def longestInst():
	longest = 0
	if segment == "..AirCmd":
		for head in Heads(SelStart(), SelEnd()):
			if ItemSize(head) > longest:
				longest = ItemSize(head)
	return longest

########################### MAIN ###########################
if __name__ == '__main__':
	yara_sig = ""
	yara_sig += "//******************************************************\n"

	if VERBOSE:
		yara_sig += "// Yara signature generated by: %s\n" % (os.path.basename(__file__))
		yara_sig += "// Generated By: %s\n" % (current_user)
		yara_sig += "// sample:    %s\n" % (GetInputFile())
		yara_sig += "// md5:       %s\n" % (GetInputFileMD5().lower())
		yara_sig += "// generated: %s\n" % (datestamp)
	else:
		yara_sig += "// sample md5:  %s\n" % (GetInputFileMD5().lower())


	yara_sig += "//******************************************************\n\n"
	yara_sig += "rule "

	if Name(SelStart()):
		yara_sig += "%s\n" % (Name(SelStart()))
	else:
		yara_sig += "offset_%x\n" % (SelStart())
	yara_sig += "{\n"

	if VERBOSE:
		yara_sig += "    meta:\n"
		yara_sig += "         author = \"%s\"\n" % (current_user)
		yara_sig += "         date   = \"%s\"\n" % (datestamp)
		yara_sig += "         desc   = \""
		if segment == "..AirCmd":
			if Name(SelStart()):
				yara_sig += "%s (0x%x-0x%x)\"\n" % (Name(SelStart()), SelStart(), SelEnd())
			else:
				yara_sig += "from: %s (0x%x-0x%x)\"\n" % (GetFunctionName(SelStart()), SelStart(), SelEnd())
		else:
			yara_sig += "%s 0x%x-0x%x\"\n" % (segment, SelStart(), SelEnd())

	yara_sig += "\n    strings:\n"

	if segment == "..AirCmd":
		max_length = longestInst()
		for head in Heads(SelStart(), SelEnd()):
			num_of_bytes = ItemEnd(head) - head
			yara_sig += "         $%x\t= {" % (head)
			for b in range(head, ItemEnd(head)+1):
				yara_sig += " %s" % (str(hex(GetOriginalByte(b)).lstrip("0x")).zfill(2))
			yara_sig += " } "
			if num_of_bytes < max_length:
				diff = max_length - num_of_bytes
				for byte_spacer in range(diff):
					yara_sig += "   "
			yara_sig += "// %s\n" % (GetDisasm(head))
		yara_sig += "\n"
	else:
		yara_sig += "         // %s:%x (%d bytes)\n" % (segment, SelStart(), SelEnd() - SelStart())
		yara_sig += "         $stream = { "
		for b in range(SelStart(), SelEnd()+1):
			yara_sig += " %s" % (str(hex(GetOriginalByte(b)).lstrip("0x")).zfill(2))
		yara_sig += " }\n\n\n"

	yara_sig += "    condition:\n"
	yara_sig += "         "

	if segment == "..AirCmd":
		heads = [ x for x in Heads(SelStart(), SelEnd()) ]
		yara_sig += "for any i in (1..#%x): (" % (heads[0])
		count = -1
		offset = 0
		for head in heads:
			count += 1
			if count == 0:
				offset += ItemSize(heads[count])
				continue
			elif count < len(heads)-1:
				yara_sig += "$%x at @%x[i]+%d and " % (head, heads[0], offset)
				offset += ItemSize(heads[count])
			else:
				yara_sig += "$%x at @%x[i]+%d)" % (head, heads[0], offset)
				offset += ItemSize(heads[count])
	else:
		yara_sig += "$stream"

	yara_sig += "\n}\n"


	outfile = AskFile(1, GetInputFileMD5().lower() + "_" + hex(SelStart())+".yar", "Save As")
	if outfile != None:
		with open(outfile, 'w') as sig:
			sig.write(yara_sig)

	print(yara_sig)

